---
- name: Add Plex repository
  deb822_repository:
    name: plex
    types: deb
    uris: https://downloads.plex.tv/repo/deb
    suites: public
    components: main
    architectures: amd64
    signed_by: https://downloads.plex.tv/plex-keys/PlexSign.key

- name: Install Plex Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: present
    update_cache: true

- name: Just force systemd to re-execute itself
  ansible.builtin.systemd_service:
    daemon_reexec: true

- name: Start and enable Plex service
  ansible.builtin.service:
    name: plexmediaserver
    state: started
    enabled: true