---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

    - name: Install yay on Arch
      include_role:
        name: jahrik.yay
      when: ansible_facts['distribution'] == 'Archlinux'

  tasks:
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 60

    - name: Check downloads existence
      ansible.builtin.stat:
        path: /mnt/media/downloads
      register: directory_check
    - name: Assert that /mnt/media/downloads exists
      ansible.builtin.assert:
        that:
          - directory_check.stat.exists
        fail_msg: Missing downloads dir
        success_msg: Success

    - name: Assert that Plex service is running
      ansible.builtin.systemd:
        name: plexmediaserver
        state: started
      register: plex_status

    - name: Assert Plex service is active and running
      ansible.builtin.assert:
        that:
          - plex_status.status.ActiveState == "active"
          - plex_status.status.SubState == "running"

    - name: Assert that Plex is responding on port 32400
      ansible.builtin.wait_for:
        host: localhost
        port: 32400
        state: started
        timeout: 10

  roles:
    - role: geerlingguy.docker
    - role: marcocot.arr_suite
