---
driver:
  name: docker
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pid: host
    privileged: true
    pre_build_image: true
    command: /usr/sbin/init
    capabilities:
    - SYS_ADMIN
  # - name: archlinux
  #   image: archlinux:latest
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: true
  #   command: /usr/sbin/init