---
- name: Install pre-requisites on Debian
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - gpg-agent
    - python3-requests
    - python3-debian
